version: "3.8"
services:
  gs:
    build:
      context: .
      dockerfile: dockerfile.golang
    env_file: ./.env
    environment:
      - MYSQL_ADDR=db
    ports:
      - 80:3000
    depends_on:
      - db

  db:
    image: mysql:8.0
    env_file: ./.env
    environment:
      - LANG=ja_JP.UTF-8
    tty: true

  db-gui:
    image: phpmyadmin/phpmyadmin
    env_file: ./.env
    environment:
      - LANG=ja_JP.UTF-8
      - PMA_ARBITRARY=1
      - PMA_HOSTS=db
      - PMA_USER=${MYSQL_USER}
      - PMA_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - 8080:80
    depends_on:
      - db

networks:
  default:
